version: '3.8'
services:
  e-commerce-app:
    build: .
    environment:
      POSTGRES_DB_HOST: postgres-db
      POSTGRES_DB_NAME: e_commerce_assignment_db
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: admin
      POSTGRES_DB_PORT: 5433
    ports:
      - "4300:4300"
    depends_on:
      - postgres-db
    networks:
      - ecommerce-net

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: e_commerce_assignment_db
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/backups
    command: -p 5433
    networks:
      - ecommerce-net

volumes:
  pgdata:

networks:
  ecommerce-net:
    driver: bridge